name: TEST MICHELE - Integration tests 
on:
  push:
    branches:
      - test-integration-michele
      # - main
      # - 'release/**'
  pull_request:
    branches:
      # - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  schedule:
    - cron: '20 16 * * *' # daily at 16:20 UTC
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        # list of os: https://github.com/actions/virtual-environments
        os:
          - ubuntu-22.04
          - macos-14
          - ubuntu-latest-erigontests-large
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: test new runner
        run: |
          set +x
          echo "I am being served by this runner: $RUNNER_NAME"
    